import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/public/styles/globals.css";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

/** Euclid Circular A */
const euclidBoldItalic = localFont({
  src: "../../public/fonts/EuclidCircularABoldItalic.ttf",
  variable: "--font-euclid-bold-italic",
});

const euclidBold = localFont({
  src: "../../public/fonts/EuclidCircularABold.ttf",
  variable: "--font-euclid-bold",
});

const euclidItalic = localFont({
  src: "../../public/fonts/EuclidCircularAItalic.ttf",
  variable: "--font-euclid-italic",
});

const euclidLightItalic = localFont({
  src: "../../public/fonts/EuclidCircularALightItalic.ttf",
  variable: "--font-euclid-light-italic",
});

const euclidLight = localFont({
  src: "../../public/fonts/EuclidCircularALight.ttf",
  variable: "--font-euclid-light",
});

const euclidMediumItalic = localFont({
  src: "../../public/fonts/EuclidCircularAMediumItalic.ttf",
  variable: "--font-euclid-medium-italic",
});

const euclidMedium = localFont({
  src: "../../public/fonts/EuclidCircularAMedium.ttf",
  variable: "--font-euclid-medium",
});

const euclidRegular = localFont({
  src: "../../public/fonts/EuclidCircularARegular.ttf",
  variable: "--font-euclid-regular",
});

const euclidSemiBoldItalic = localFont({
  src: "../../public/fonts/EuclidCircularASemiBoldItalic.ttf",
  variable: "--font-euclid-semibold-italic",
});

const euclidSemiBold = localFont({
  src: "../../public/fonts/EuclidCircularASemiBold.ttf",
  variable: "--font-euclid-semibold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${euclidBoldItalic.variable}
          ${euclidBold.variable}
          ${euclidItalic.variable}
          ${euclidLightItalic.variable}
          ${euclidLight.variable}
          ${euclidMediumItalic.variable}
          ${euclidMedium.variable}  
          ${euclidRegular.variable}
          ${euclidSemiBoldItalic.variable}
          ${euclidSemiBold.variable}
          antialiased
          bg-background,
          max-w-[1000px]
          mx-auto
        `}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;